spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/shop
    password: 1488
    username: postgres
  flyway:
    baseline-on-migrate: true
